# Generated by Django 6.0.5 on 2026-05-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_promocode_vacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='specialization',
        ),
        migrations.AddField(
            model_name='employee',
            name='specialization',
            field=models.ManyToManyField(blank=True, to='core.specialization', verbose_name='Специализации'),
        ),
    ]
