# Generated by Django 6.0.5 on 2026-05-19 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_employee_specialization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_order_status', 'Может менять статус заказа'), ('can_edit_master_note', 'Может редактировать заметки мастера')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'ordering': ['-is_active', '-created_at'], 'permissions': [('can_use_promocode', 'Может использовать промокоды')], 'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
