# Generated by Django 6.0.5 on 2026-05-20 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_order_status', 'Может менять статус заказа'), ('can_edit_master_note', 'Может редактировать заметки мастера'), ('can_create_order', 'Может создавать заказы'), ('can_use_promocode', 'Может использовать промокоды')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма скидки'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.promocode', verbose_name='Применённый промокод'),
        ),
    ]
